version: '3.7'

services:
  bank:
    container_name: bankapp
    build:
      context: ./bank
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ACCOUNTANT_PASSWORD=1023e6fecf51d27627bf2eed2f7feded
      - REDIS_HOST=redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - internal
  redis:
    container_name: redis
    image: "redis:6.2.5-alpine3.14"
    networks:
      - internal
  accountant:
    container_name: accountant
    build:
      context: ./accountant
      dockerfile: Dockerfile
    environment:
      - ACCOUNTANT_PASSWORD=1023e6fecf51d27627bf2eed2f7feded
    depends_on:
      - redis
      - bank
    networks:
      - internal
networks:
  internal:
    driver: bridge


